dist: xenial
language: python
cache: pip
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- py.test
- flake8
deploy:
  provider: pypi
  user: __token__
  password:
    secure: WkiId4SXifRX2bBo3me7lNGxdUk0tUrbAG7HqeaTcbCSUotp/9RrQ8WwvFK/42/4ovV+v1WUX0L6emT2UrGDg2Wf7wRkajz19uQgrMhZkuegocge7FDepPRktoFroxJh1yx8KWtNcTZI7L1TVsb3xchhZQ82TpV78Y44de/23q/0tCXwSGtgq7+RozufYjeXVRxyZhctsJX3TCDKHfK4vkVSmPPEWyIePcuk0d+CrhVBXmaAiRzKiTpDu+DnoYtr5+zZTANO2ccZ+jYRtlMF3u06dSSpuLvZkFUhUzZrjohaN8nd/LTNNyXqSiUarmnhq+Z0va7dmp65TFPF/SzKxyDOXBtyhy8A1/8feQHfXuOTEzKWwSsst8k1VKjcMpsl25jibsLyRtP+EO43TEq41ekDPtNV/qYAEoF8gLEZQCNK4G6FofXjREOvDXKLNGZkUaXcXg/H1lfXgkSXdQn/e/iaExV5on+uYAFxMQxvSjFjb2oSl1la4i/J9YREus2RLC8iGfPXoM3LArepKcv0pTQ6GnYxb6mgp8DJkvamEIFzhdlOsrnfJ7kUN9L1BBOqs4S+BrFNm558esYhrpZbWVwIj9V0YyetfKt5ci8gMRRKrJyEFDLAtNYXiTkAnqlqDakkJeTnFs46plTr3tqk4OQEX2xVrQtCR4CdbX6Er6U=
  on:
    branch: master
    tags: true
